In Java 11, we get the following error message for the NPE:
java.lang.NullPointerException

In Java 17, we get a much nicer error message from NPEs:

java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "cs" is null

So, change the assertion to use "withMessageContaining" so that it
will work in both 11 and 17.

Also, remove unused import of Optional from KiwiPrimitives